spring:
  application:
    name: ChatBot Service

server:
  port: 8080


gemini:
  api:
    key: ${GEMINI_API_KEY:}  # working with .env variable
    model: gemini-2.5-flash
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent